# Generated by Django 4.1.7 on 2023-03-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='city',
            name='image',
        ),
    ]
