# Generated by Django 4.1.7 on 2023-03-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_rename_description_city_content_remove_city_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='img',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='content',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
